// src/components/Footer.svelte
<style>
  .footer {
    text-decoration: none;
    text-transform: uppercase;
    color: #3b3e49;
    display: inline-block;
    width: 100%;
    text-align: center;
  }

  .footer .line {
    margin: 40px auto 20px auto;
    height: 1px;
    display: block;
    width: 150px;
    background-color: #e6e7e9;
  }

  .footer a {
    text-decoration: none;
    text-transform: uppercase;
    color: #3b3e49;
    padding: 10px 0;
    display: block;
    font-weight: 800;
  }
</style>

<footer class="footer">
  <div class="line"></div>
  <a href="mailto:jgatjens@gmail.com">Hire me</a>
</footer>

// src/components/Footer.tsx

import React from 'react'
import styled from 'styled-components'

const Footer = styled.div`
  text-decoration: none;
  text-transform: uppercase;
  color: #3B3E49;
  display: inline-block;
  width: 100%;
  text-align: center;

  .line {
    margin: 40px auto 20px auto;
    height: 1px;
    display: block;
    width: 150px;
    background-color: #E6E7E9;
  }

  a {
    text-decoration: none;
    text-transform: uppercase;
    color: #3B3E49;
    padding: 10px 0;
    display: block;
    font-weight: 800;
  }
    
`

export default () => (
  <Footer>
    <div className="line"></div>
    <a href="mailto:jgatjens@gmail.com">Hire me</a>
  </Footer>
)
